apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsql-cm
data:
  hostname: "pgsql-0.pgsql"


